# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  joint_a1: 0.6
  joint_a2: 0.45
  joint_a3: -0.2
  joint_a4: -1.0
  joint_a5: 0.3
  joint_a6: -0.2
  joint_a7: 0.45
